Update read.ino
I got the following error if i compiled with these lines active:" \core\core_9a74a1942bafa06a2f266b27df654d4d.a(HardwareSerial.cpp.o):(.bss.Serial1+0x0): multiple definition of `Serial1'
sketch\read.ino.cpp.o:(.bss.Serial1+0x0): first defined here
collect2.exe: error: ld returned 1 exit status "

This was solved by removing the hardwareSerial definition.
Defining HardwareSerial for ESP32 is no longer necessary to my knowledge, therefore it is commented out. Hardware serial is present in \cores\esp32\HardwareSerial.cpp.

Also, see this thread for more info https://github.com/reaper7/SDM_Energy_Meter/issues/25